#!/bin/bash

cat $1 | ./jefa > Main.java 
rm -f comperrors 
rm -f Main.class
javac -cp $JEFA Main.java 2> ./comperrors

if [ ! -f Main.class  ]; then
    echo "Sintax Error. See more at comperrors"
fi
rm -f Main.java
