file ::= statement
statement ::= statement statement
	| WHILE LPAREN expression RPAREN LCURLY statement RCURLY 
	| SEMICOL 
	| IF LPAREN expression RPAREN LCURLY statement RCURLY
	| definition SEMICOL 
	| assignment SEMICOL
	| function SEMICOL
	| expression SEMICOL 
	| operand SEMICOL
definition ::= 
	type assignment 
	| type ID
type ::= INT_T
	| AUTO_T
	| STRING_T
expression : operand boperator operand
	| OPP expression 
	| LPAREN expression RPAREN AND LPAREN expression RPAREN
	| LPAREN expression RPAREN OR LPAREN expression RPAREN
	| LPAREN expression RPAREN
	| TRUE
	| FALSE
boperator ::= EQCOMP 
	| NE 
	| LT 
	| GT
	| LE 
	| GE
	| ACC	
operand ::=  primary
	| operand operator operand 
	| uop primary  
	| SUB INT
	| ADD INT
uop ::= TOREGEXP
	| MIN 
	| DET 
	| COMP 
primary ::= ID
	| built_in 
	| LPAREN operand RPAREN 
	| uop primary
built_in ::= STRING 
	 | INT
operator ::= ADD
	| SUB 
	| AND
	| OR
	| MUL
	| DIV 
	| CONCAT
assignment ::= ID EQASS operand 
function ::= PRINT fargs
	| GRAPH fargs
	| SCAN ID
fargs ::= expression 
	| operand 
